Add flip node
GraphiteEditor/Graphite pull request #1367
Opened 2023-08-06 14:26 UTC by ShouvikGhosh2048

2023-08-06 14:37 UTC, TrueDoctor commented
@Keavon does it make sense to have all of these options exposed for the flip nodes? I would have probably only added very limited controls and removed options like shear and translation and used a transform node instead.
The Flip node is a strict subset of what the Transform node can do so I would argue that its purpose should be to be a very simple wrapper for the full transform node which is a bit easier to use and as soon as you need more features, you can chain a translate node. But I'm not sure if that is what makes most sense from a users perspective

2023-08-06 16:25 UTC, Keavon commented
"Flip X" and "Flip Y" are the two parameters I'd like this node to have.

2023-08-06 22:23 UTC, TrueDoctor commented
> "Flip X" and "Flip Y" are the two parameters I'd like this node to have.

And pivot I would assume

2023-08-06 23:49 UTC, Keavon commented
> And pivot I would assume

Just within the bounding box I would think.

2023-08-07 03:49 UTC, ShouvikGhosh2048 commented
The node currently only allows the user to choose `Horizontal` or `Vertical` from a dropdown (I'll change this to `FlipX` and `FlipY`) - the `transform`, `scale`, `rotation`, `skew` and `pivot` inputs are only there to get the current transform, scale, etc. Is there a better way to get these values?

2023-08-08 08:43 UTC, TrueDoctor requested changes

2023-08-08 08:43 UTC, TrueDoctor commented on editor/src/messages/portfolio/document/node_graph/node_graph_message_handler/document_node_types.rs
> +				DocumentInputType::value("Skew", TaggedValue::DVec2(DVec2::ZERO), false),
```suggestion
```

2023-08-08 08:43 UTC, TrueDoctor commented on node-graph/gcore/src/transform.rs
> +	pub(crate) shear: Shear,
```suggestion
```

2023-08-08 08:43 UTC, TrueDoctor commented on node-graph/gcore/src/transform.rs
> +	let modification = pivot * DAffine2::from_scale_angle_translation(new_scale, rotate as f64, translate) * DAffine2::from_cols_array(&[1., shear.y, shear.x, 1., 0., 0.]) * pivot.inverse();
```suggestion
pub(crate) fn flip_vector_data<Data: TransformMut>(mut data: Data, flip_x: bool, flip_y: bool, pivot: DVec2) -> Data {
	let pivot = DAffine2::from_translation(data.local_pivot(pivot));
	let bool_to_scale = |b| if b { -1. } else { 1. }
	let new_scale = DVec2::new(bool_to_scale(flip_x), bool_to_scale(flip_y));

	let modification = pivot * DAffine2::from_scale(new_scalee)  * pivot.inverse();
```

2023-08-08 08:43 UTC, TrueDoctor commented on node-graph/interpreted-executor/src/node_registry.rs
> +		register_node!(graphene_core::transform::FlipNode<_, _, _, _, _, _, _>, input: WasmSurfaceHandleFrame, params: [bool, bool, DVec2, f32, DVec2, DVec2, DVec2]),
```suggestion
		register_node!(graphene_core::transform::FlipNode<_, _, _>, input: VectorData, params: [bool, bool, DVec2]),
		register_node!(graphene_core::transform::FlipNode<_, _, _>, input: ImageFrame<Color>, params: [bool, bool, DVec2),
		register_node!(graphene_core::transform::FlipNode<_, _, _>, input: WasmSurfaceHandleFrame, params: [bool, bool, DVec2]),
```

2023-08-11 08:08 UTC, TrueDoctor approved these changes

2023-08-27 21:26 UTC, Keavon commented
Just checking what this is held up on.

2023-08-28 00:51 UTC, ShouvikGhosh2048 commented
The `update_bounds` drift issue.

2023-08-28 00:56 UTC, Keavon commented
@TrueDoctor is that something you'd be able to help with?

2023-10-28 20:56 UTC, 0HyperCube commented
!build

2023-11-04 09:53 UTC, Keavon commented
Closing this for now since it's been inactive for a while. Feel free to reopen it if it's revived.

2023-11-04 09:53 UTC, closed without merging