properties panel remains active when user edits text layer
GraphiteEditor/Graphite pull request #2144
Opened 2024-12-17 20:56 UTC by Sidharth-Singh10

Closes #2127

- Introduced the `active_panel` field in `DocumentMessageHandle`r to track the currently active interface panel.
- Added a match expression in `set_editing` fn to verify if the active panel is the Properties Panel, preventing its deselection during edits.

https://github.com/user-attachments/assets/dd34f593-b3e0-4f54-b65a-f8cde3af87ff

2024-12-17 21:43 UTC, 0HyperCube approved these changes
Works well; thanks for this contribution.

2024-12-18 20:33 UTC, Keavon commented
@adamgerhant could you please review this in regards to the introduced ActivePanel code, to make sure it doesn't conflict with your existing implementation of the related concept of the active panel used for showing whether the graph's subnetwork or Layers panel is active?

2024-12-19 02:03 UTC, adamgerhant requested changes
The active panel is currently being stored in the portfolio message handler. There is no need to store it in the document message handler.

2024-12-19 09:58 UTC, 0HyperCube commented
@adamgerhant the text tool code can't access the portfolio message handler.

2024-12-19 18:37 UTC, adamgerhant commented
It could be passed as a parameter, but I think it makes sense for the active panel to be stored on a per document basis instead of the entire portfolio/application. This means switching tabs will store independent active panel states. In this case the active panel should be removed from the portfolio message handler.

2024-12-19 19:31 UTC, adamgerhant commented
Why not just leave the text layer as selected when editing ends?

2024-12-19 21:24 UTC, Sidharth-Singh10 commented
I haven't worked much with design tools much, but doesn't keeping text layers selected after editing deviates from standard design tool patterns where edits typically end in deselection.
Persistent selection might create risk for accidental modifications - users may unintentionally resize/move/style the text layer when they meant to work on something else.

In this implementation the layer while in editing is deselected when clicked anywhere else expect properties panel

2024-12-20 00:56 UTC, adamgerhant approved these changes

2024-12-20 09:17 UTC, Keavon commented
@Sidharth-Singh10 I like where you're going with that thought process, although I believe for consistency with other drawing tools in Graphite, it would be best to keep it selected after clicking out. If you draw with any other tool like Rectangle or Ellipse, you'll notice if you look in the Layers panel, that layer remains selected after finishing drawing it. So it'd be best if the layer remains selected if you click anywhere in the viewport, or anywhere else in the UI, after interactively editing the text. Thanks :)

2024-12-20 09:18 UTC, Keavon requested changes
See my previous comment for the updated approach, thanks!

2024-12-20 21:44 UTC, Keavon commented on editor/src/messages/portfolio/document/document_message_handler.rs
> +
```suggestion
```

2024-12-20 21:45 UTC, Keavon commented
!build

2024-12-20 22:36 UTC, Keavon commented
Can I have you add another little improvement to this PR while I'm thinking about it? If the user is editing the interactive text in the viewport, and hits escape, it should delete the entire text layer if escape was pressed when the text was empty. So if a user creates text in the wrong spot but doesn't type anything (or types then deletes it all), escape will delete the layer so it doesn't get invisibly stuck behind.

2024-12-21 19:26 UTC, Keavon commented
!build

2024-12-22 02:10 UTC, Keavon commented
!build

2024-12-22 02:13 UTC, Keavon commented
It looks like <kbd>Escape</kbd> is working but right-click isn't for canceling an empty text layer for it to get deleted. Can you please look into making it work when it's empty and the user right-clicks?

(Also note that I rebased, so you'll need to pull before continuing to code on it.)

2024-12-22 07:43 UTC, Sidharth-Singh10 commented
Hey @Keavon, I added an entry for `MouseRight` with `action_dispatch` set to `TextToolMessage::CommitText` in `input_mapping.rs`, but it doesn't seem to have any effect.

To confirm I was editing the correct location, I commented out the `MouseLeft` entry with `action_dispatch` set to `TextToolMessage::Interact`. This prevented placing or editing text, which suggests my changes are indeed in the right place.

Could you nudge me in the right direction?

2024-12-22 09:22 UTC, Keavon commented
I'll ping @0HyperCube to see if he can answer your question about that.

2024-12-23 10:31 UTC, 0HyperCube commented
@Sidharth-Singh10 

The actions that are advertised to the input mapper system don't include the commit text when the text is not being edited:
```rs
fn actions(&self) -> ActionList {
	match self.fsm_state {
		TextToolFsmState::Ready => actions!(TextToolMessageDiscriminant;
			Interact,
		),
		TextToolFsmState::Editing => actions!(TextToolMessageDiscriminant;
			Interact,
			Abort,
			CommitText,
		),
	}
}
```

Any time any mouse button is pressed that is not inside the text input, `input.ts:175` sends `editor.handle.onChangeText` which sets editing to false.

2024-12-23 11:23 UTC, Sidharth-Singh10 commented
Thanks for pointing this out!

2024-12-23 18:40 UTC, Keavon commented
!build

2024-12-23 21:07 UTC, Keavon commented
@Sidharth-Singh10 your solution to emulate an escape keypress from the frontend TS code is a hack that works but isn't very clean. Can you please take into account what Hypercube wrote and implement a solution in the backend Rust code? In other words, you need to have something run before the tool state leaves `Editing` and returns to `Ready` to check if that TS code he mentioned is causing it to return to `Ready`.

2024-12-24 23:35 UTC, Keavon commented
!build

2024-12-31 22:27 UTC, Keavon approved these changes

2024-12-31 22:28 UTC, merged