Navigation
GraphiteEditor/Graphite pull request #229
Opened 2021-06-27 14:32 UTC by 0HyperCube

Solves #155
TODO
- [x] Panning with mmb
- [ ] Panning support for laptops (to discuss)
- [x] Add viewport size to the IPP (perhaps with some suspicious vue code)
- [x] Make document centred
- [x] Allow rotation with left click drag
- [ ] Allow zooming with <kbd>ctrl</kbd> + scroll
- [ ] Allow zooming with <kbd>+</kbd> and <kbd>-</kbd> keys
- [ ] Allow zooming with widgets

2021-06-27 19:53 UTC, Keavon commented
> Allow rotation with left click drag

If this is referring to the Navigate Tool's functionality, just a little correction: zoom is left click drag (up and down), rotation is right click drag (around the center). Should be very easy to swap though :)

2021-06-27 21:00 UTC, Keavon commented
I need to think more about laptop layouts but for now, I think the most likely set of input controls that apply to all tools is MMB to pan, Ctrl+MMB to zoom, and Shift+MMB to rotate. So the current ability to rotate from any tool with RMB-drag, before we merge this, would ideally be changed to Shift+MMB drag. Then for the Navigate Tool, when that's implemented (#155), it'll be a separate set of controls which don't require the modifier keys.

2021-07-03 11:34 UTC, Keavon commented
It looks like currently you can zoom with just the <kbd>+</kbd> and <kbd>-</kbd> keys without even holding down the <kbd>Ctrl</kbd> modifier. Could this be changed to require the modifier?

2021-07-03 13:10 UTC, 0HyperCube commented
> It looks like currently you can zoom with just the + and - keys without even holding down the Ctrl modifier. Could this be changed to require the modifier?

@Keavon Done

2021-07-03 13:18 UTC, TrueDoctor reviewed
> Reviewed 2 of 9 files at r3, 1 of 2 files at r4, 3 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/229)* status: 6 of 14 files reviewed, 1 unresolved discussion (waiting on @0HyperCube)

___
*[core/editor/src/frontend/frontend_message_handler.rs, line 23 at r5](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MdgVFJv1zBdMOmg0THc:-MdgVFJv1zBdMOmg0THd:bcyrciz) ([raw file](https://github.com/graphiteeditor/graphite/blob/944039b8cecb4d09dc7324dee3886b0900e34ec1/core/editor/src/frontend/frontend_message_handler.rs#L23)):*
> ```
> 	UpdateZoom { change: f64 },
> ```
the naming is probably a bit confusing, what do you think about something like this?
SetZoomLevel{zoom_level: f64}
ZoomIn{amount: f64}
ZoomOut{amount: f64}


<!-- Sent from Reviewable.io -->

2021-07-11 12:18 UTC, Keavon commented on client/web/src/components/widgets/inputs/NumberInput.vue
>  			}
Math.min I think you mean?

2021-07-11 12:18 UTC, Keavon commented on client/web/src/components/widgets/inputs/NumberInput.vue
> +			this.text = Math.round(this.value) + this.unit;
Please use backtick template strings instead of + concatenation.

2021-07-11 12:18 UTC, Keavon commented on client/web/src/components/widgets/inputs/NumberInput.vue
> +			const new_value = parseInt(newText, 10);
camelCase

2021-07-11 12:18 UTC, Keavon commented on client/web/src/components/widgets/inputs/NumberInput.vue
> +			const new_value = this.clampValue(newValue, resetOnClamp);
camelCase

2021-07-11 12:33 UTC, 0HyperCube reviewed
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/229)* status: 1 of 20 files reviewed, 7 unresolved discussions (waiting on @Keavon and @TrueDoctor)

___
*[client/web/src/components/panels/Document.vue, line 336 at r8](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MdCsjcyWqi12p3TYGyf-r8-336:-MeKXib96hyjta6jAhdy:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/891f78e110c0ce8932f42e1577a84eb9e8673bd4/client/web/src/components/panels/Document.vue#L336)):*
<details><summary><i>Previously, Keavon (Keavon Chambers) wrote…</i></summary><blockquote>

Technically the `DOMContentLoaded` would be safer and more of a good practice than the `load` event here.
</blockquote></details>

Done.
___
*[client/web/src/components/widgets/inputs/NumberInput.vue, line 101 at r8](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MdOCCbcsehSB9UMgdCn-r8-101:-MeKXjKE-9k1uxjMyUOP:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/891f78e110c0ce8932f42e1577a84eb9e8673bd4/client/web/src/components/widgets/inputs/NumberInput.vue#L101)):*
<details><summary><i>Previously, Keavon (Keavon Chambers) wrote…</i></summary><blockquote>

These should be camelCase not snake_case per JS conventions. Let's please also try to use full words: mult -> multiplier.
</blockquote></details>

Done.
___
*[client/web/src/components/widgets/inputs/NumberInput.vue, line 125 at r8](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MdOCCbcsehSB9UMgdCn-r8-125:-MeKXmvP8IQgYN3OfvX2:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/891f78e110c0ce8932f42e1577a84eb9e8673bd4/client/web/src/components/widgets/inputs/NumberInput.vue#L125)):*
<details><summary><i>Previously, Keavon (Keavon Chambers) wrote…</i></summary><blockquote>

camelCase
</blockquote></details>

Done.
___
*[client/web/src/components/widgets/inputs/NumberInput.vue, line 139 at r8](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MdOCCbcsehSB9UMgdCn-r8-139:-MeKXnRbEknGPFH4ztWS:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/891f78e110c0ce8932f42e1577a84eb9e8673bd4/client/web/src/components/widgets/inputs/NumberInput.vue#L139)):*
<details><summary><i>Previously, Keavon (Keavon Chambers) wrote…</i></summary><blockquote>

Math.min I think you mean?
</blockquote></details>

Done.
___
*[client/web/src/components/widgets/inputs/NumberInput.vue, line 144 at r8](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MdOCCbcsehSB9UMgdCn-r8-144:-MeKYgtIBhKR6MkTx0XP:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/891f78e110c0ce8932f42e1577a84eb9e8673bd4/client/web/src/components/widgets/inputs/NumberInput.vue#L144)):*
<details><summary><i>Previously, Keavon (Keavon Chambers) wrote…</i></summary><blockquote>

Please use backtick template strings instead of + concatenation.
</blockquote></details>

Done.
___
*[client/web/src/components/widgets/inputs/NumberInput.vue, line 147 at r8](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MdOCCbcsehSB9UMgdCn-r8-147:-MeKYhFqCeEG44-aZYZS:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/891f78e110c0ce8932f42e1577a84eb9e8673bd4/client/web/src/components/widgets/inputs/NumberInput.vue#L147)):*
<details><summary><i>Previously, Keavon (Keavon Chambers) wrote…</i></summary><blockquote>

camelCase
</blockquote></details>

Done.
___
*[core/editor/src/frontend/frontend_message_handler.rs, line 23 at r5](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MdgVFJv1zBdMOmg0THc:-Mdgi15F8apenvwfPtfR:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/944039b8cecb4d09dc7324dee3886b0900e34ec1/core/editor/src/frontend/frontend_message_handler.rs#L23)):*
<details><summary><i>Previously, TrueDoctor wrote…</i></summary><blockquote>

> ```
> 	UpdateZoom { change: f64 },
> ```
the naming is probably a bit confusing, what do you think about something like this?
SetZoomLevel{zoom_level: f64}
ZoomIn{amount: f64}
ZoomOut{amount: f64}
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-11 13:32 UTC, TrueDoctor requested changes
> Reviewed 1 of 9 files at r3, 7 of 15 files at r6, 7 of 10 files at r7, 4 of 4 files at r8, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/229)* status: all files reviewed, 16 unresolved discussions (waiting on @0HyperCube and @Keavon)

___
*[core/editor/src/document/document_file.rs, line 89 at r8](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MeKXD0M2Gz66OFlbzq-:-MeKXD0M2Gz66OFlbzq0:b-lwd8un) ([raw file](https://github.com/graphiteeditor/graphite/blob/891f78e110c0ce8932f42e1577a84eb9e8673bd4/core/editor/src/document/document_file.rs#L89)):*
> ```XML
> 
> impl LayerData {
> 	pub fn new(expanded: bool) -> LayerData {
> ```

We could open an issue for using some sort of builder pattern here if we keep adding data to the struct
___
*[core/editor/src/document/document_file.rs, line 99 at r8](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MeKXV_4EIonZgxqfUNv:-MeKXV_4EIonZgxqfUNw:bwjd5zb) ([raw file](https://github.com/graphiteeditor/graphite/blob/891f78e110c0ce8932f42e1577a84eb9e8673bd4/core/editor/src/document/document_file.rs#L99)):*
> ```XML
> 		}
> 	}
> 	pub fn get_snapped_rotation(&self) -> f64 {
> ```

per rust convention we don't write out the get. get_snapped_transform -> snapped_transform.
shouldn't the snapping take place before setting the value? -- I see why that would not work now, a more general function that is used by this one would still be nice tough
I would expect a 
```rust
fn snap_to_angle(angle: f32, increments: f32) -> f32
```
this  should also improve reusability for the code
___
*[core/editor/src/document/document_file.rs, line 107 at r8](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MeKYxDv8lEyahUg_OfA:-MeKYxDv8lEyahUg_OfB:b-6rzci4) ([raw file](https://github.com/graphiteeditor/graphite/blob/891f78e110c0ce8932f42e1577a84eb9e8673bd4/core/editor/src/document/document_file.rs#L107)):*
> ```XML
> 		}
> 	}
> 	pub fn get_transform(&self) -> DAffine2 {
> ```

this can be simplified to 
self.offset_transform((0,0).into())
___
*[core/editor/src/document/document_file.rs, line 113 at r8](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MeKYV9p0fKMubDl7CAs:-MeKYV9p0fKMubDl7CAt:b7agnsm) ([raw file](https://github.com/graphiteeditor/graphite/blob/891f78e110c0ce8932f42e1577a84eb9e8673bd4/core/editor/src/document/document_file.rs#L113)):*
> ```XML
> 		angle_transform * scale_transform * translation_transform
> 	}
> 	pub fn get_offset_transform(&self, offset: DVec2) -> DAffine2 {
> ```

you should be able to remove the braces
___
*[core/editor/src/document/document_message_handler.rs, line 100 at r8](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MeKZmh84M3GfTi4ptNm:-MeKZmh906BxCpDy_tYO:b-secjka) ([raw file](https://github.com/graphiteeditor/graphite/blob/891f78e110c0ce8932f42e1577a84eb9e8673bd4/core/editor/src/document/document_message_handler.rs#L100)):*
> ```XML
> 		self.active_document_mut().layer_data.get_mut(&path).expect("Layerdata does not exist")
> 	}
> 	fn _create_transform_from_layerdata(&self, path: Vec<u64>, responses: &mut VecDeque<Message>) {
> ```

is the underscore a typo?
___
*[core/editor/src/document/document_message_handler.rs, line 101 at r8](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MeK_Gdx3MSJ4oMsZa6p:-MeK_Gdx3MSJ4oMsZa6q:b-bg47ca) ([raw file](https://github.com/graphiteeditor/graphite/blob/891f78e110c0ce8932f42e1577a84eb9e8673bd4/core/editor/src/document/document_message_handler.rs#L101)):*
> ```XML
> 	}
> 	fn _create_transform_from_layerdata(&self, path: Vec<u64>, responses: &mut VecDeque<Message>) {
> 		let layerdata = self.active_document().layer_data.get(&path).expect("Layerdata does not exist");
> ```

would it be possible/make sense to just generate the layer_data in that case?
___
*[core/editor/src/document/document_message_handler.rs, line 110 at r8](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MeKjKFh9qcfpD0iVSvt:-MeKjKFh9qcfpD0iVSvu:bf09bmd) ([raw file](https://github.com/graphiteeditor/graphite/blob/891f78e110c0ce8932f42e1577a84eb9e8673bd4/core/editor/src/document/document_message_handler.rs#L110)):*
> ```XML
> 		);
> 	}
> 	fn create_document_transform_from_layerdata(&self, ipp: &InputPreprocessor, responses: &mut VecDeque<Message>) {
> ```

I would in general prefer to just pass the size directly instead of a ref to the input Preprocessor but this is fine
___
*[core/editor/src/document/document_message_handler.rs, line 111 at r8](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MeK_qBv2I7cv0X-SGom:-MeK_qBwCwXekGlN89lK:b-4trqwf) ([raw file](https://github.com/graphiteeditor/graphite/blob/891f78e110c0ce8932f42e1577a84eb9e8673bd4/core/editor/src/document/document_message_handler.rs#L111)):*
> ```XML
> 	}
> 	fn create_document_transform_from_layerdata(&self, ipp: &InputPreprocessor, responses: &mut VecDeque<Message>) {
> 		let half_viewport = DVec2::new(ipp.viewport_size.x as f64 / 2., ipp.viewport_size.y as f64 / 2.);
> ```

You can probably just do DVec2(…size.x, …size.y) /2.
it would probably also make sense to add a to_vec2() method on viewport_size
___
*[core/editor/src/document/document_message_handler.rs, line 396 at r8](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MeKab2h0dt0V2_wP7rC:-MeKab2h0dt0V2_wP7rD:bxlexcr) ([raw file](https://github.com/graphiteeditor/graphite/blob/891f78e110c0ce8932f42e1577a84eb9e8673bd4/core/editor/src/document/document_message_handler.rs#L396)):*
> ```XML
> 			MouseMove => {
> 				if self.translating {
> 					let delta = DVec2::new(ipp.mouse.position.x as f64 - self.mouse_pos.x as f64, ipp.mouse.position.y as f64 - self.mouse_pos.y as f64);
> ```

Same applies here:
let delta = ipp.mouse.position.to_vec2() - self.mouse.position.to_vec2()
___
*[core/editor/src/input/input_mapper.rs, line 190 at r8](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MeKkwXY-XtBvHi4zshc:-MeKkwXY-XtBvHi4zshd:bbk8yw6) ([raw file](https://github.com/graphiteeditor/graphite/blob/891f78e110c0ce8932f42e1577a84eb9e8673bd4/core/editor/src/input/input_mapper.rs#L190)):*
> ```XML
> 			entry! {action=DocumentMessage::TranslateDown, key_down=Mmb},
> 			entry! {action=DocumentMessage::TransformUp, key_up=Mmb},
> 			entry! {action=DocumentMessage::MultiplyZoom(1.25), key_down=KeyPlus, modifiers=[KeyControl]},
> ```

These should be exposed as constants somewhere


<!-- Sent from Reviewable.io -->

2021-07-11 14:20 UTC, TrueDoctor reviewed
It would also be nice to get a constant for the snap angle, we basically want a constant for everything that is user configurable.
This also makes it easier to implement something like settings from which you can modify these

> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/229#-:-MeKqXW50yOLooIvvw0b:b3axjcg)* status: 18 of 20 files reviewed, 16 unresolved discussions (waiting on @0HyperCube, @Keavon, and @TrueDoctor)



<!-- Sent from Reviewable.io -->

2021-07-11 14:53 UTC, 0HyperCube reviewed
> Dismissed @Keavon and @TrueDoctor from 11 discussions.
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/229)* status: 17 of 21 files reviewed, 5 unresolved discussions (waiting on @0HyperCube, @Keavon, and @TrueDoctor)

___
*[core/editor/src/document/document_file.rs, line 89 at r8](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MeKXD0M2Gz66OFlbzq-:-MeKmrFWEX7MJBDcbDSV:b32w0x) ([raw file](https://github.com/graphiteeditor/graphite/blob/891f78e110c0ce8932f42e1577a84eb9e8673bd4/core/editor/src/document/document_file.rs#L89)):*
<details><summary><i>Previously, TrueDoctor wrote…</i></summary><blockquote>

We could open an issue for using some sort of builder pattern here if we keep adding data to the struct
</blockquote></details>

OK
___
*[core/editor/src/document/document_file.rs, line 99 at r8](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MeKXV_4EIonZgxqfUNv:-MeKq07859uhaWzt_nfi:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/891f78e110c0ce8932f42e1577a84eb9e8673bd4/core/editor/src/document/document_file.rs#L99)):*
<details><summary><i>Previously, TrueDoctor wrote…</i></summary><blockquote>

per rust convention we don't write out the get. get_snapped_transform -> snapped_transform.
shouldn't the snapping take place before setting the value? -- I see why that would not work now, a more general function that is used by this one would still be nice tough
I would expect a 
```rust
fn snap_to_angle(angle: f32, increments: f32) -> f32
```
this  should also improve reusability for the code
</blockquote></details>

Done.
___
*[core/editor/src/document/document_file.rs, line 107 at r8](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MeKYxDv8lEyahUg_OfA:-MeL24g32kj7IwMOsT5s:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/891f78e110c0ce8932f42e1577a84eb9e8673bd4/core/editor/src/document/document_file.rs#L107)):*
<details><summary><i>Previously, TrueDoctor wrote…</i></summary><blockquote>

this can be simplified to 
self.offset_transform((0,0).into())
</blockquote></details>

Done.
___
*[core/editor/src/document/document_file.rs, line 113 at r8](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MeKYV9p0fKMubDl7CAs:-MeL245z9IuVzfLaaWYk:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/891f78e110c0ce8932f42e1577a84eb9e8673bd4/core/editor/src/document/document_file.rs#L113)):*
<details><summary><i>Previously, TrueDoctor wrote…</i></summary><blockquote>

you should be able to remove the braces
</blockquote></details>

Done.
___
*[core/editor/src/document/document_message_handler.rs, line 100 at r8](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MeKZmh84M3GfTi4ptNm:-MeL-2jD3ZT-Xbvyfy90:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/891f78e110c0ce8932f42e1577a84eb9e8673bd4/core/editor/src/document/document_message_handler.rs#L100)):*
<details><summary><i>Previously, TrueDoctor wrote…</i></summary><blockquote>

is the underscore a typo?
</blockquote></details>

Done.
___
*[core/editor/src/document/document_message_handler.rs, line 101 at r8](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MeK_Gdx3MSJ4oMsZa6p:-MeL-1VHBQWYfUqWSTu-:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/891f78e110c0ce8932f42e1577a84eb9e8673bd4/core/editor/src/document/document_message_handler.rs#L101)):*
<details><summary><i>Previously, TrueDoctor wrote…</i></summary><blockquote>

would it be possible/make sense to just generate the layer_data in that case?
</blockquote></details>

Done.
___
*[core/editor/src/document/document_message_handler.rs, line 110 at r8](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MeKjKFh9qcfpD0iVSvt:-MeL-cKw2ksImuHGR2NY:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/891f78e110c0ce8932f42e1577a84eb9e8673bd4/core/editor/src/document/document_message_handler.rs#L110)):*
<details><summary><i>Previously, TrueDoctor wrote…</i></summary><blockquote>

I would in general prefer to just pass the size directly instead of a ref to the input Preprocessor but this is fine
</blockquote></details>

Done.
___
*[core/editor/src/document/document_message_handler.rs, line 111 at r8](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MeK_qBv2I7cv0X-SGom:-MeL-eqk6e7f4cq4NFLY:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/891f78e110c0ce8932f42e1577a84eb9e8673bd4/core/editor/src/document/document_message_handler.rs#L111)):*
<details><summary><i>Previously, TrueDoctor wrote…</i></summary><blockquote>

You can probably just do DVec2(…size.x, …size.y) /2.
it would probably also make sense to add a to_vec2() method on viewport_size
</blockquote></details>

Done.
___
*[core/editor/src/document/document_message_handler.rs, line 396 at r8](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MeKab2h0dt0V2_wP7rC:-MeL2ACa2o3lkCnoeIax:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/891f78e110c0ce8932f42e1577a84eb9e8673bd4/core/editor/src/document/document_message_handler.rs#L396)):*
<details><summary><i>Previously, TrueDoctor wrote…</i></summary><blockquote>

Same applies here:
let delta = ipp.mouse.position.to_vec2() - self.mouse.position.to_vec2()
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-11 15:04 UTC, TrueDoctor requested changes
> Reviewed 1 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/229)* status: 18 of 21 files reviewed, 8 unresolved discussions (waiting on @0HyperCube, @Keavon, and @TrueDoctor)

___
*[core/editor/src/document/document_file.rs, line 100 at r11](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MeL2T0c8-6_suVAgh4X:-MeL2T0c8-6_suVAgh4Y:b7cn0y2) ([raw file](https://github.com/graphiteeditor/graphite/blob/1f5eb6cef06df766d169c860b5a38e4520766a66/core/editor/src/document/document_file.rs#L100)):*
> ```XML
> 	}
> 	pub fn snapped_angle(&self, increment: f64) -> f64 {
> 		let increment_radians: f64 = std::f64::consts::PI / (180. / increment);
> ```

you can also use increment.to_radians()
___
*[core/editor/src/document/document_message_handler.rs, line 102 at r11](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MeL3bsT6uK_VM6ikGnX:-MeL3bsT6uK_VM6ikGnY:b-7ltmds) ([raw file](https://github.com/graphiteeditor/graphite/blob/1f5eb6cef06df766d169c860b5a38e4520766a66/core/editor/src/document/document_message_handler.rs#L102)):*
> ```XML
> 	}
> 	fn get_layerdata_mut(&mut self, path: &[LayerId]) -> &mut LayerData {
> 		if self.active_document_mut().layer_data.contains_key(path) {
> ```

you can use hashmap.entry() here: https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.entry
I also believe your current code would not work, afaik insert returns the element that was replaced, in this case it would always return None
___
*[core/editor/src/input/mouse.rs, line 36 at r11](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MeL5-NN7eJwYEk7LCpl:-MeL5-NN7eJwYEk7LCpm:b-4nu2ea) ([raw file](https://github.com/graphiteeditor/graphite/blob/1f5eb6cef06df766d169c860b5a38e4520766a66/core/editor/src/input/mouse.rs#L36)):*
> ```XML
> 	}
> 	pub fn distance(&self) -> f64 {
> 		self.x as f64 + self.y as f64 + self.z as f64
> ```

whait, why no square root?
also you could probably do something like self.to_vec2().distance()


<!-- Sent from Reviewable.io -->

2021-07-11 18:30 UTC, 0HyperCube reviewed
> Dismissed @TrueDoctor from a discussion.
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/229)* status: 17 of 23 files reviewed, 7 unresolved discussions (waiting on @0HyperCube, @Keavon, and @TrueDoctor)

___
*[core/editor/src/document/document_file.rs, line 100 at r11](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MeL2T0c8-6_suVAgh4X:-MeLoaAC1owne_6trUsp:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/1f5eb6cef06df766d169c860b5a38e4520766a66/core/editor/src/document/document_file.rs#L100)):*
<details><summary><i>Previously, TrueDoctor wrote…</i></summary><blockquote>

you can also use increment.to_radians()
</blockquote></details>

Done.
___
*[core/editor/src/document/document_message_handler.rs, line 102 at r11](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MeL3bsT6uK_VM6ikGnX:-MeLovqjAZj2gELs_a6m:b-gkq4xm) ([raw file](https://github.com/graphiteeditor/graphite/blob/1f5eb6cef06df766d169c860b5a38e4520766a66/core/editor/src/document/document_message_handler.rs#L102)):*
<details><summary><i>Previously, TrueDoctor wrote…</i></summary><blockquote>

you can use hashmap.entry() here: https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.entry
I also believe your current code would not work, afaik insert returns the element that was replaced, in this case it would always return None
</blockquote></details>

@truedoctor The current code will work as I do not return the result from the insert but instead have another get_mut below it
___
*[core/editor/src/input/input_mapper.rs, line 190 at r8](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MeKkwXY-XtBvHi4zshc:-MeLp6pe6rbcpQXYjU5O:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/891f78e110c0ce8932f42e1577a84eb9e8673bd4/core/editor/src/input/input_mapper.rs#L190)):*
<details><summary><i>Previously, TrueDoctor wrote…</i></summary><blockquote>

These should be exposed as constants somewhere
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-11 18:56 UTC, 0HyperCube reviewed
> Dismissed @TrueDoctor from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/229)* status: 17 of 23 files reviewed, 5 unresolved discussions (waiting on @Keavon and @TrueDoctor)

___
*[core/editor/src/document/document_message_handler.rs, line 102 at r11](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MeL3bsT6uK_VM6ikGnX:-MeLqFwCDas7G6ll-fsX:bnoxo2m) ([raw file](https://github.com/graphiteeditor/graphite/blob/1f5eb6cef06df766d169c860b5a38e4520766a66/core/editor/src/document/document_message_handler.rs#L102)):*
<details><summary><i>Previously, 0HyperCube wrote…</i></summary><blockquote>

@truedoctor The current code will work as I do not return the result from the insert but instead have another get_mut below it
</blockquote></details>

Done, I was looking for something like that but failed to find it
___
*[core/editor/src/input/mouse.rs, line 36 at r11](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MeL5-NN7eJwYEk7LCpl:-MeLvGbs3TnZ0d8rPSXY:bd8vkor) ([raw file](https://github.com/graphiteeditor/graphite/blob/1f5eb6cef06df766d169c860b5a38e4520766a66/core/editor/src/input/mouse.rs#L36)):*
<details><summary><i>Previously, TrueDoctor wrote…</i></summary><blockquote>

whait, why no square root?
also you could probably do something like self.to_vec2().distance()
</blockquote></details>

Done, I was unsure how this should work as I've never used scroll X before


<!-- Sent from Reviewable.io -->

2021-07-11 21:02 UTC, TrueDoctor reviewed
> Reviewed 3 of 5 files at r13, 1 of 1 files at r14, 1 of 1 files at r15.
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/229)* status: 22 of 23 files reviewed, 4 unresolved discussions (waiting on @Keavon and @TrueDoctor)

___
*[core/editor/src/input/mouse.rs, line 36 at r11](https://reviewable.io/reviews/graphiteeditor/graphite/229#-MeL5-NN7eJwYEk7LCpl:-MeMK4fJCsteFFRTeUrh:b-u39k1n) ([raw file](https://github.com/graphiteeditor/graphite/blob/1f5eb6cef06df766d169c860b5a38e4520766a66/core/editor/src/input/mouse.rs#L36)):*
<details><summary><i>Previously, 0HyperCube wrote…</i></summary><blockquote>

Done, I was unsure how this should work as I've never used scroll X before
</blockquote></details>

It does feel pretty weird atm. I'm am pretty sure that it should be sqrt(x*x + y*y + z*z)
but it would probably also good to do this based on your starting location.
If i currently move to the top right on my trackpad, x is incremented and y is decremented causing a weird glitchy effect.
That could b resolved if we could somehow use the total amount that you moved since you started dragging (I know that that is probably very difficult or impossible) but you might also have ideas how we could solve this


<!-- Sent from Reviewable.io -->

2021-07-11 21:03 UTC, TrueDoctor requested changes
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/229)* status: 22 of 23 files reviewed, 5 unresolved discussions (waiting on @0HyperCube, @Keavon, and @TrueDoctor)



<!-- Sent from Reviewable.io -->

2021-07-11 21:28 UTC, TrueDoctor commented
Not sure that is supposed to happen: 
![image](https://user-images.githubusercontent.com/21245806/125210362-a9b7bb00-e29f-11eb-92a7-3cbd500985a1.png)

2021-07-12 07:09 UTC, Keavon commented on core/editor/src/document/document_message_handler.rs
> +				let scroll = ipp.mouse.scroll_delta.to_dvec2().length();
`length()` is presumably always positive, so it only zooms in. You can probably get the intended behavior by separating out the horizontal and vertical components and using the one with a greater absolute value (so a slight horizontal scroll would be ignored compared to the larger magnitude vertical scroll that's either positive or negative).

2021-07-12 20:59 UTC, Keavon commented
Ok, last finishing touches: could you please cap the zoom to the range of, say, 0.000_001% and 1_000_000%?

(Also, `initial_value` and `update_on_callback` should be camelCase in the JS code)

2021-07-13 05:41 UTC, TrueDoctor reviewed
> Reviewed 1 of 2 files at r16, 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/229)* status: 15 of 23 files reviewed, 5 unresolved discussions (waiting on @0HyperCube, @Keavon, and @TrueDoctor)



<!-- Sent from Reviewable.io -->

2021-07-13 05:41 UTC, TrueDoctor approved these changes

2021-07-13 06:48 UTC, Keavon approved these changes
> Reviewed 4 of 8 files at r18, 4 of 4 files at r19.
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/229)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @0HyperCube)



<!-- Sent from Reviewable.io -->

2021-07-13 06:49 UTC, Keavon commented
I'll go ahead and merge this now and make those couple tiny fixes in a subsequent commit.

2021-07-13 06:50 UTC, merged