Implement function to find inflection points of a Bezier curve
GraphiteEditor/Graphite pull request #712
Opened 2022-07-03 15:14 UTC by linda-zheng

Implemented `unrestricted_inflections` and `inflections`  functions in bezier-rs directory.
- `unrestricted_inflections` finds the t-values corresponding to the inflection points of the curve.
- `inflections` calls `unrestricted_inflections` and filters the t-values, only keeping the t-values between [0, 1].

 Added inflection section to the UI.

2022-07-03 19:40 UTC, RobNadal requested changes
I think we should test the alternative implementation for inflection which involves rotating the curve, to see if it's a cleaner solution. @hannahli2010 already has that functionality on the line-intersection branch, so it shouldnt be too difficult.

2022-07-03 19:40 UTC, RobNadal commented on bezier-rs/docs/interactive-docs/wasm/src/lib.rs
> +		JsValue::from_serde(&serde_json::to_string(&inflections).unwrap()).unwrap()
Could we create a template function that does the `serde` / `json` wrapping and then use it both here and in extrema?

2022-07-14 01:42 UTC, RobNadal approved these changes

2022-07-27 01:14 UTC, Keavon commented on bezier-rs/lib/src/lib.rs
> +				match rotated_bezier.handles {
Use `if let` instead of `match`.

2022-07-28 02:31 UTC, Keavon commented on bezier-rs/lib/src/lib.rs
> +				match rotated_bezier.handles {
@linda-zheng thanks for the changes. For future reference, please click "Resolve conversation" for anything that's been taken care of so it simplifies the view of what's left to be done. Thanks for the 👍 though, I've gone ahead and clicked resolve on all the ones you gave that reaction for.

2022-07-28 02:33 UTC, Keavon commented
We have some merge conflicts as a result of the PR that merged today, and one unresolved comment from Rob. If we can resolve those issues, feel free to hit merge.

2022-07-28 02:52 UTC, merged